### ISSUE TITLE
Unable to import MSTL

### ISSUE THREAD

**Issue by virsto** [KishManani/MSTL#1]
I am using Python 3.9 and statsmodels 0.13.2 (latest via PIP) on a Windows 10 platform and the following code:

``
import matplotlib.pyplot as plt
from   pandas.plotting import register_matplotlib_converters
from   statsmodels.datasets import co2
from   statsmodels.tsa.seasonal import MSTL

register_matplotlib_converters()
data = co2.load().data
data = data.resample('M').mean().ffill()

res = STL(data).fit()
res.plot()
plt.show()
``
gives the following error 

File "C:\PythonTestCode\Forecasting-Prediction\stl_plot.py", line 4, in <module>
  from statsmodels.tsa.seasonal import MSTL

builtins.ImportError: cannot import name 'MSTL' from 'statsmodels.tsa.seasonal' (C:\Python39\lib\site-packages\statsmodels\tsa\seasonal.py)

How can I fix this?

**Comment by KishManani** [comment]
> I am using Python 3.9 and statsmodels 0.13.2 (latest via PIP) on a Windows 10 platform and the following code:

The version of Statsmodels that contains MSTL is not yet on PyPI because it was added to Statsmodels recently. If you want to reproduce the results in the notebook, I suggest following the instructions in the README and installing the requirements in the `requirements.txt` file in a virtual environment. I've pinned a version of Statsmodels in the requirements file that does contain the MSTL code. Alternatively, you can install the latest version of Statsmodels from the master branch on GitHub. Let me know if that helps!

**Comment by virsto** [comment]
Thanks KishManani for your prompt reply :-)

When will MSTL be available in Statsmodels? Here is what I have installed as per your requirements.txt:

jupyterlab = 3.4.3
matplotlib = 3.5.2
numpy      = 1.23.0
pandas      = 1.4.0
seaborn     = 0.11.2

Not sure how to access/use the following:

  git+https://github.com/statsmodels/statsmodels.git@74836e9cf2198ac7a930146405da7239c0823a9b#egg=statsmodels

I did find your [MSTL code](https://www.statsmodels.org/devel/_modules/statsmodels/tsa/stl/mstl.html)

How can I install your MSTL code to execute without a virtual environment and Jupyter? Or, how can I install the latest Statsmodels code that you mentioned with your MSTL?

As you can probably tell by now, I am not that good with Git :-(
